# Generated by Django 4.2 on 2023-04-21 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_rename_author_like_account_like_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
    ]
