# Generated by Django 4.2 on 2023-04-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_remove_like_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="account",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
